name: Run test file

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Script to test the unittests
        run: python3 -m unittest tests/test.py
